### ISSUE TITLE
House Renting System

### ISSUE THREAD

**Issue by shreyamaurya029** [alexcg1/good-first-issues#60]
Idea: The idea is to  develop a system where users would get to know about cheap houses which are available in their desired locality.

Tech Stack: HTML, CSS, JS,Java

Motivation behind this idea: Often people move to different cities for jobs and other purposes. The major issue they face is of housing and rentals. Through this system they would get to know about houses that are available for rent in their desired locality at cheaper price. They can directly get in contact with the house owner and can have better idea about the house and its condition.

**Comment by rutikal** [comment]
i would like to work on this issue

**Comment by muskaan04** [comment]
i would like to work on this?
